'use client'

import { useEffect, useRef, useState } from 'react'
import { Header, type RecentBundle } from '../components/Header'
import { Intro } from '../components/Intro'
import { InstallView } from '../components/InstallView'
import { JourneyView } from '../components/JourneyView'
import { TraceView } from '../components/TraceView'
import { SinkView } from '../components/SinkView'
import { ResourceLinks } from '../components/ResourceLinks'
import { Icon } from '../components/Icon'
import { CommandPalette } from '../components/CommandPalette'
import { starter, normalize, type App } from '../lib/lachesis'
import { trackEvent } from '../lib/analytics'

type View = 'trace' | 'journey' | 'investigate' | 'install'
type LoadState = {type:'idle'|'loading'|'success'|'error';message:string}

export default function Page() {
  const [view,setView]=useState<View>('trace'); const [direction,setDirection]=useState<'backward'|'forward'>('backward'); const [app,setApp]=useState<App>(starter); const [menu,setMenu]=useState(false); const [dark,setDark]=useState(true); const [flowId,setFlowId]=useState(starter.flows[0].id); const [stepId,setStepId]=useState(starter.flows[0].steps[0].node_id); const [entryIndex,setEntryIndex]=useState(0); const [hopId,setHopId]=useState(starter.entries[0].hops[0].node_id); const [sinkId,setSinkId]=useState(starter.nodes.find(node=>node.kind==='sink')?.id??''); const [query,setQuery]=useState(''); const [loadState,setLoadState]=useState<LoadState>({type:'idle',message:''}); const [isDemo,setIsDemo]=useState(true); const [dragActive,setDragActive]=useState(false); const [commandOpen,setCommandOpen]=useState(false); const [inspectorOpen,setInspectorOpen]=useState(true); const [recentBundles,setRecentBundles]=useState<RecentBundle[]>([]); const [urlReady,setUrlReady]=useState(false); const fileRef=useRef<HTMLInputElement>(null)

  useEffect(()=>{const stored=window.localStorage.getItem('lachesis-theme');if(stored==='light')setDark(false)},[])
  useEffect(()=>{try{const stored=JSON.parse(window.localStorage.getItem('lachesis-recent-bundles')??'[]');if(Array.isArray(stored))setRecentBundles(stored.filter(item=>item&&typeof item.name==='string'&&typeof item.loadedAt==='number').slice(0,3))}catch{window.localStorage.removeItem('lachesis-recent-bundles')}},[])
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';window.localStorage.setItem('lachesis-theme',dark?'dark':'light')},[dark])
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const nextView=params.get('view');if(nextView==='trace'||nextView==='journey'||nextView==='investigate'||nextView==='install')setView(nextView);const nextFlow=params.get('flow');const flow=starter.flows.find(item=>item.id===nextFlow);if(flow){setFlowId(flow.id);const node=params.get('node');if(node&&flow.steps.some(step=>step.node_id===node))setStepId(node)}const entryId=params.get('entry');const index=starter.entries.findIndex(item=>item.id===entryId);if(index>=0){setEntryIndex(index);const hop=params.get('hop');if(hop&&starter.entries[index].hops.some(item=>item.node_id===hop))setHopId(hop)}const sink=params.get('sink');if(sink&&starter.nodes.some(node=>node.id===sink&&node.kind==='sink'))setSinkId(sink);if(params.get('direction')==='forward')setDirection('forward');setUrlReady(true)},[])
  useEffect(()=>{if(!urlReady)return;const url=new URL(window.location.href);url.searchParams.set('view',view);if(view==='trace'){url.searchParams.set('flow',flowId);url.searchParams.set('node',stepId);url.searchParams.set('direction',direction);['entry','hop','sink'].forEach(key=>url.searchParams.delete(key))}else if(view==='journey'){url.searchParams.set('entry',app.entries[entryIndex]?.id??'');url.searchParams.set('hop',hopId);['flow','node','direction','sink'].forEach(key=>url.searchParams.delete(key))}else if(view==='investigate'){url.searchParams.set('sink',sinkId);['flow','node','direction','entry','hop'].forEach(key=>url.searchParams.delete(key))}else{['flow','node','direction','entry','hop','sink'].forEach(key=>url.searchParams.delete(key))}window.history.replaceState({},'',url)},[urlReady,view,flowId,stepId,direction,entryIndex,hopId,sinkId,app.entries])
  useEffect(()=>{function onKeyDown(event:KeyboardEvent){const target=event.target as HTMLElement;const editing=target.matches('input, textarea, select, [contenteditable="true"]');if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setCommandOpen(open=>!open);return}if(event.key==='Escape'){setCommandOpen(false);setMenu(false);setInspectorOpen(false);return}if(editing)return;if(event.key==='/'&&view==='trace'){event.preventDefault();document.querySelector<HTMLInputElement>('.search input')?.focus()}if(view==='trace'&&event.key==='ArrowLeft'){setDirection('backward');trackEvent('trace_direction_changed',{direction:'backward',source:'keyboard'})}if(view==='trace'&&event.key==='ArrowRight'){setDirection('forward');trackEvent('trace_direction_changed',{direction:'forward',source:'keyboard'})}}window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[view])

  function activate(next:App){setApp(next);setFlowId(next.flows[0].id);setStepId(next.flows[0].steps[0].node_id);setEntryIndex(0);setHopId(next.entries[0]?.hops[0]?.node_id??next.nodes[0].id);setSinkId(next.nodes.find(node=>node.kind==='sink'||next.flows.some(flow=>flow.steps.some(step=>step.node_id===node.id&&step.role==='sink')))?.id??'');setMenu(false);setInspectorOpen(true);setIsDemo(false);setLoadState({type:'success',message:`Loaded ${next.name || 'bundle.json'}.`});const recent:RecentBundle={name:next.name||'Untitled bundle',language:next.language||'unknown',commit:next.commit||'no commit',lines:next.lines,flows:next.flows.length,loadedAt:Date.now()};setRecentBundles(current=>{const updated=[recent,...current.filter(item=>`${item.name}:${item.commit}`!==`${recent.name}:${recent.commit}`)].slice(0,3);window.localStorage.setItem('lachesis-recent-bundles',JSON.stringify(updated));return updated});trackEvent('bundle_loaded',{has_callpaths:next.entries.length>0,flow_count:next.flows.length})}
  async function upload(file?:File){if(!file)return;setLoadState({type:'loading',message:`Reading ${file.name}…`});try{const text=await file.text();let raw:unknown;try{raw=JSON.parse(text)}catch{throw new Error('This file is not valid JSON.')}activate(normalize(raw))}catch(error){setLoadState({type:'error',message:`${error instanceof Error?error.message:'Could not read bundle.json'} The current bundle was kept.`});trackEvent('bundle_load_failed')}finally{setDragActive(false)}}

  return <main className="app-shell" id="top" onDragEnter={event=>{event.preventDefault();setDragActive(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={event=>{if(event.currentTarget===event.target)setDragActive(false)}} onDrop={event=>{event.preventDefault();upload(event.dataTransfer.files?.[0])}}><Header view={view} setView={setView} app={app} menu={menu} setMenu={setMenu} onUpload={()=>fileRef.current?.click()} onCommand={()=>setCommandOpen(true)} dark={dark} setDark={setDark} recentBundles={recentBundles}/><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={event=>{upload(event.target.files?.[0]);event.target.value='' }}/>{commandOpen&&<CommandPalette app={app} onClose={()=>setCommandOpen(false)} onView={next=>setView(next)} onFlow={(nextFlow,nextNode)=>{setView('trace');setFlowId(nextFlow);setStepId(nextNode);setInspectorOpen(true)}} onEntry={(nextIndex,nextHop)=>{setView('journey');setEntryIndex(nextIndex);setHopId(nextHop);setInspectorOpen(true)}} onSink={nextSink=>{setView('investigate');setSinkId(nextSink)}}/>}{dragActive&&<div className="drop-overlay" role="presentation"><div><span className="drop-glyph"><Icon name="upload" size={22}/></span><b>Drop bundle.json to inspect</b><small>Your current bundle changes only after validation succeeds.</small></div></div>}<Intro view={view} app={app} loadState={loadState} isDemo={isDemo} onUpload={()=>fileRef.current?.click()}/>{view==='trace'&&<TraceView app={app} flowId={flowId} setFlowId={setFlowId} stepId={stepId} setStepId={setStepId} query={query} setQuery={setQuery} direction={direction} setDirection={setDirection} inspectorOpen={inspectorOpen} onInspectorOpen={()=>setInspectorOpen(true)} onInspectorClose={()=>setInspectorOpen(false)}/>} {view==='journey'&&<JourneyView app={app} entryIndex={entryIndex} setEntryIndex={setEntryIndex} hopId={hopId} setHopId={setHopId} inspectorOpen={inspectorOpen} onInspectorOpen={()=>setInspectorOpen(true)} onInspectorClose={()=>setInspectorOpen(false)}/>} {view==='investigate'&&<SinkView app={app} sinkId={sinkId} setSinkId={setSinkId} onRecord={()=>{}} onOpenFlow={(nextFlow,nextNode)=>{setView('trace');setFlowId(nextFlow);setStepId(nextNode);setInspectorOpen(true)}}/>} {view==='install'&&<InstallView onUpload={()=>fileRef.current?.click()}/>}<ResourceLinks/><footer><span><i className="status-dot"/> Active bundle: <b>{app.name}</b></span><span>Shortcuts: <b>⌘K</b> jump · <b>/</b> search · <b>← →</b> direction · <b>Esc</b> close</span><span className="footer-brand">Lachesis · graph reader</span></footer></main>
}
