'use client'
import { Icon } from './Icon'
import type { App } from '../lib/lachesis'
import { trackEvent } from '../lib/analytics'

type View = 'home'|'trace'|'journey'|'investigate'|'map'|'compare'|'install'
export type RecentBundle = {name:string;language:string;commit:string;lines:number;flows:number;loadedAt:number}
type Props = { view:View; setView:(view:View)=>void; app:App; menu:boolean; setMenu:(open:boolean)=>void; onUpload:()=>void; onCommand:()=>void; dark:boolean; setDark:(dark:boolean)=>void; recentBundles:RecentBundle[] }
const views: Array<{id:View;label:string;detail:string}> = [{id:'home',label:'Briefing',detail:'Start here'},{id:'investigate',label:'Investigate',detail:'Find convergence'},{id:'map',label:'Explore',detail:'See topology'},{id:'compare',label:'Compare',detail:'Review revisions'}]
export function Header({view,setView,app,menu,setMenu,onUpload,onCommand,dark,setDark,recentBundles}:Props) {
  return <div className="topbar-wrap"><header className="topbar"><a className="brand" href="#top" aria-label="Lachesis Explorer home"><span className="brand-mark"><i/><i/><i/></span><span><b>Lachesis</b><small>evidence explorer</small></span></a><nav className="nav-tabs" aria-label="Analysis lenses">{views.map(item=><button key={item.id} className={view===item.id?'nav-tab active':'nav-tab'} onClick={()=>{setView(item.id);trackEvent('view_changed',{view:item.id})}}><span>{item.label}</span><small>{item.detail}</small></button>)}</nav><div className="header-actions"><button className="command-trigger" onClick={onCommand} aria-label="Open command palette"><Icon name="search" size={14}/><span>Jump</span><kbd>⌘K</kbd></button><button className="theme-toggle" aria-label={`Switch to ${dark?'light':'dark'} mode`} onClick={()=>{setDark(!dark);trackEvent('theme_toggled',{theme:dark?'light':'dark'})}}><Icon name={dark?'sun':'moon'} size={15}/><span>{dark?'Light':'Dark'}</span></button><div className="app-picker"><button className="repo-control" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-haspopup="dialog"><span className="status-dot"/><span><small>Active bundle</small><b>{app.name || 'Untitled bundle'}</b></span><Icon name="chevron" size={14}/></button>{menu&&<div className="app-menu" role="dialog" aria-label="Bundle context"><span className="menu-title">BUNDLE CONTEXT</span><div className="active-bundle"><span className="status-dot"/><span><b>{app.name || 'Untitled bundle'}</b><small>{app.language || 'unknown'} · {app.commit || 'no commit'}</small></span></div><div className="menu-metrics"><span><b>{app.nodes.length}</b> nodes</span><span><b>{app.flows.length}</b> flows</span><span><b>{app.entries.length}</b> paths</span></div>{recentBundles.length>0&&<div className="recent-bundles"><span className="menu-title">RECENT METADATA · LOCAL ONLY</span>{recentBundles.map(item=><div className="recent-bundle" key={`${item.name}:${item.commit}`}><span><b>{item.name}</b><small>{item.language} · {item.commit}</small></span><em>{item.flows} flows</em></div>)}</div>}<button className="upload-action" onClick={()=>{onUpload();trackEvent('bundle_upload_started')}}><span>Load another bundle</span><span className="button-icon"><Icon name="upload" size={14}/></span></button></div>}</div></div></header></div>
}
