'use client'
import { useState } from 'react'
import type { LayoutPoint, Node, Step } from '../lib/lachesis'

export type PathItem = { id:string; node:Node; label:string; caption?:string; edge?:Step['edge'] }
type Props = { items:PathItem[]; selectedId:string; onSelect:(id:string)=>void; points?:Array<LayoutPoint|undefined>; layoutSource:'precomputed'|'derived' }
const shorten=(value:string,limit=18)=>value.length>limit?`${value.slice(0,limit-1)}…`:value

export function PathCanvas({items,selectedId,onSelect,points,layoutSource}:Props) {
  const [viewport,setViewport]=useState<'fit'|'reset'>('fit')
  const resolved=items.map((_,index)=>points?.[index]??{x:78+index*(564/Math.max(1,items.length-1)),y:116})
  const xs=resolved.map(point=>point.x);const ys=resolved.map(point=>point.y)
  const minX=Math.min(0,...xs)-48;const maxX=Math.max(672,...xs)+48;const minY=Math.min(0,...ys)-52;const maxY=Math.max(220,...ys)+72
  const viewBox=viewport==='fit'?`${minX} ${minY} ${maxX-minX} ${maxY-minY}`:'0 0 720 250'
  return <div className="path-canvas"><div className="canvas-bar"><div><span className="canvas-title">Evidence path</span><span className="canvas-count">{items.length} nodes</span></div><div className="canvas-actions"><span className={`layout-source ${layoutSource}`}><i/>{layoutSource==='precomputed'?'Bundle layout':'Derived layout'}</span><button className={viewport==='fit'?'active':''} aria-pressed={viewport==='fit'} onClick={()=>setViewport('fit')}>Fit</button><button className={viewport==='reset'?'active':''} aria-pressed={viewport==='reset'} onClick={()=>setViewport('reset')}>Reset</button></div></div><div className="canvas-viewport"><svg viewBox={viewBox} aria-hidden="true" focusable="false">{resolved.slice(0,-1).map((point,index)=>{const next=resolved[index+1];const edge=items[index+1]?.edge;const edgeClass=edge?.dynamic?'dynamic':edge?.alias?'alias':'exact';return <g key={`edge-${index}`}><path className={`path-edge ${edgeClass}`} d={`M${point.x+30} ${point.y} C${point.x+62} ${point.y},${next.x-62} ${next.y},${next.x-30} ${next.y}`}/>{edgeClass!=='exact'&&<text className={`edge-caption ${edgeClass}`} x={(point.x+next.x)/2} y={(point.y+next.y)/2-10} textAnchor="middle">{edgeClass}</text>}</g>})}{items.map((item,index)=>{const point=resolved[index];const selected=item.id===selectedId;return <g key={`${item.id}-${index}`} className={`path-node kind-${item.node.kind}${selected?' selected':''}`} onClick={()=>onSelect(item.id)}><circle className="node-halo" cx={point.x} cy={point.y} r="38"/><circle className="node-body" cx={point.x} cy={point.y} r="29"/><text className="node-index" x={point.x} y={point.y+4} textAnchor="middle">{String(index+1).padStart(2,'0')}</text><text className="node-role" x={point.x} y={point.y+50} textAnchor="middle">{shorten(item.label,16)}</text><text className="node-file" x={point.x} y={point.y+66} textAnchor="middle">{shorten(item.node.file.split('/').pop()||item.node.file,18)}</text></g>})}</svg></div><div className="path-index-list" aria-label="Evidence path nodes">{items.map((item,index)=><button key={`${item.id}-${index}`} className={item.id===selectedId?'selected':''} onClick={()=>onSelect(item.id)} aria-pressed={item.id===selectedId}><span>{String(index+1).padStart(2,'0')}</span><b>{item.label}</b><small>{item.node.label} · {item.node.file}:{item.node.line}{item.edge?.alias?' · alias':''}{item.edge?.dynamic?' · dynamic':''}</small></button>)}</div><div className="graph-legend" aria-label="Graph color legend"><span><i className="legend-exact"/>exact path</span><span><i className="legend-alias"/>alias</span><span><i className="legend-dynamic"/>dynamic</span><span><i className="legend-sink"/>sink</span></div></div>
}
