'use client'
import type { App } from '../lib/lachesis'
import { indirectionCount } from '../lib/lachesis'
import { trackEvent } from '../lib/analytics'
import { Icon } from './Icon'
import { PathCanvas, type PathItem } from './PathCanvas'
import { NodeInspector } from './NodeInspector'
import { EvidencePanel } from './EvidencePanel'
type Props={app:App;flowId:string;setFlowId:(v:string)=>void;stepId:string;setStepId:(v:string)=>void;query:string;setQuery:(v:string)=>void;direction:'backward'|'forward';setDirection:(v:'backward'|'forward')=>void;inspectorOpen:boolean;onInspectorOpen:()=>void;onInspectorClose:()=>void}
export function TraceView({app,flowId,setFlowId,stepId,setStepId,query,setQuery,direction,setDirection,inspectorOpen,onInspectorOpen,onInspectorClose}:Props){const flow=app.flows.find(item=>item.id===flowId)??app.flows[0];const selected=app.nodes.find(node=>node.id===stepId)??app.nodes[0];const visible=app.flows.filter(item=>item.name.toLowerCase().includes(query.toLowerCase()));const steps=direction==='backward'?flow.steps:[...flow.steps].reverse();const evidence=app.mcp.find(item=>item.for===flow.id);const items:PathItem[]=steps.map(step=>({id:step.node_id,node:app.nodes.find(node=>node.id===step.node_id)??app.nodes[0],label:step.role,caption:step.note,edge:step.edge}));return <section className={`workspace${inspectorOpen?'':' inspector-closed'}`}><aside className="sidebar"><span className="panel-label">VALUES & SYMBOLS</span><label className="search"><Icon name="search" size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filter values" aria-label="Filter values"/></label><div className="node-list">{visible.length?visible.map(item=><button key={item.id} className={flow.id===item.id?'node-row selected':'node-row'} onClick={()=>{setFlowId(item.id);setStepId(item.steps[0]?.node_id??'');onInspectorOpen();trackEvent('flow_selected')}}><span className="kind-dot"/><span><b>{item.name}</b><small>{item.steps.length} nodes · {indirectionCount(item)} indirect</small></span></button>):<p className="list-empty">No matching values.</p>}</div><div className="sidebar-foot"><span className="tiny-dot"/> {app.flows.length} flows available</div></aside><main className="main-panel"><div className="toolbar"><div><span className="panel-label">SELECTED VALUE</span><h2><code>{flow.name}</code></h2></div><div className="toolbar-actions">{!inspectorOpen&&<button className="inspector-reopen" onClick={onInspectorOpen}>Show source</button>}<div className="segmented" aria-label="Trace direction"><button className={direction==='backward'?'selected':''} onClick={()=>{setDirection('backward');trackEvent('trace_direction_changed',{direction:'backward'})}}>comes from</button><button className={direction==='forward'?'selected':''} onClick={()=>{setDirection('forward');trackEvent('trace_direction_changed',{direction:'forward'})}}>goes to</button></div></div></div><PathCanvas items={items} selectedId={stepId} onSelect={id=>{setStepId(id);onInspectorOpen();trackEvent('trace_node_selected')}} layoutSource="derived"/><EvidencePanel evidence={evidence} fallbackTool="reaches" fallbackArgs={flow.name} fallbackSummary={`${steps.length} visible nodes in this value-flow path.`} nodeCount={steps.length} indirections={indirectionCount(flow,evidence)}/></main>{inspectorOpen&&<NodeInspector node={selected} onClose={onInspectorClose}/>}</section>}
